apiVersion: v1
kind: Pod
metadata:
  name: localdomain-customer-setup
  labels:
    app: localdomain-customer-setup
spec:
  containers:
  - name: localdomain-customer-setup
    image: localhost:5000/customer:latest
    # command: ["sh", "-c", "ls -la /export/config/solr/conf && sleep 30"]
    command: ["sh", "-c", "apk --no-cache add curl zip && (cd /export/config/solr/conf && zip -r - *) | curl -X POST --header 'Content-Type:application/octet-stream' --data-binary @- 'http://localhost:8983/solr/admin/configs?action=UPLOAD&name=customer' && curl -X POST --header 'Content-Type:application/json;charset=utf-8' 'http://localhost:8983/solr/admin/collections?_=1571830773677&action=CREATE&autoAddReplicas=false&collection.configName=customer&maxShardsPerNode=1&name=customer&numShards=1&replicationFactor=1&router.name=compositeId&wt=json'"]
    imagePullPolicy: Always
  imagePullSecrets:
  - name: registry-credentials
